elasticsearch:
  ip: "10.0.0.1"
  port: 9200
  user: "tempuser"
  pass: "passwordfromelastic"
  index: "winlogbeat-*" # please modify before each query, can be "winlogbeat-*", "auditbeat-*", "*", but please don't run a "*" unless you know what you're doing
  verify_certs: false
  ssl_show_warn: false
  request_timeout: 6000
  completion_timeout: "500s"
  query_size: 300
  search_filter: {"range": {"@timestamp": {"gte": "now-4w","lte": "now"}}}

eql_queries:
  # - potential disabling of selinux: |
  #     any where event.category == "process" and host.os.type == "linux" and (event.type == "start" or event.type == "process_started") and process.name == "setenforce" and process.args == "0"
  - sus linux after connection: |
      sequence by host.hostname with maxspan=1s
        [ process where process.args regex ".*bin.*" ]
        [ network where related.ip == "77.241.193.242" ]
        [ process where host.hostname == "112app" ]
  # - base64 with powershell_script_block_text exists: |
  #       any where process.parent.args regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)" and process.parent.name != "jp2launcher.exe" and process.parent.args != "*java*"
  - rundll32 with base64 in args nearby network activity: |
      sequence by agent.name with maxspan=1s
        [network where true]
        [process where process.name == "rundll32.exe" and (process.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)" or process.parent.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)")]
  # - rundll32 with base64 in args: |
  #     process where process.name == "rundll32.exe" and (process.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)" or process.parent.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)")
  - dns nearby command executables: |
      sequence by agent.name with maxspan=1s
        [dns where dns.question.name exists]
        [process where (process.name in ("rundll32.exe", "powershell.exe", "cmd.exe") or process.parent.name in ("rundll32.exe", "powershell.exe", "cmd.exe"))]
  - dns nearby command executables with base64:
      sequence by agent.name with maxspan=1s
        [dns where dns.question.name exists]
        [process where (process.name in ("rundll32.exe", "powershell.exe", "cmd.exe") or process.parent.name in ("rundll32.exe", "powershell.exe", "cmd.exe")) and 
          (process.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)" or 
          process.parent.command_line regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)")]
  # - base64 executed in any process arguments: |
  #     process where event.type in ("start", "process_started") and process.args regex "([A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)" and not process.command_line : ("*SYSVOL*", "*Userman*", "*sc*") and not process.parent.command_line : ("*SYSVOL*", "*Userman*", "*sc*")
  # - login near stun vpn activity: |
  #     sequence by agent.name with maxspan=30s
  #       [ network where source.port == 5349 or destination.port == 5349 ]
  #       [ event where event.category == "authentication" ]
  # - find php webshell persistence in nginx: |
  #     sequence with maxspan=60s
  #     [ any where related.ip == 77.241.193.242 ]
  #     [ any where process.name: *php* ]
  - regsvr32 ran and process creation: |
     sequence with maxspan=7m
     [ process where event.type == "creation" ] by process.executable
     [ library where process.name == "regsvr32.exe" ] by dll.path with runs=2
  - dll side loading via microsoft programs: |
      process where host.os.type == "windows" and event.type == "start" and
      process.pe.original_file_name in ("WinWord.exe", "EXPLORER.EXE", "w3wp.exe", "DISM.EXE") and
      not (process.name : ("winword.exe", "explorer.exe", "w3wp.exe", "Dism.exe") or
            process.executable : ("?:\\Windows\\explorer.exe",
                                  "?:\\Program Files\\Microsoft Office\\root\\Office*\\WINWORD.EXE",
                                  "?:\\Program Files?(x86)\\Microsoft Office\\root\\Office*\\WINWORD.EXE",
                                  "?:\\Windows\\System32\\Dism.exe",
                                  "?:\\Windows\\SysWOW64\\Dism.exe",
                                  "?:\\Windows\\System32\\inetsrv\\w3wp.exe")
            )
